 TABLE public."SymbaApi_usermaster" (
    user_id uuid NOT NULL,
    firstname character varying(30) NOT NULL,
    middlename character varying(30),
    lastname character varying(30) NOT NULL,
    description character varying(200),
    email character varying(50) NOT NULL,
    usertype_id integer,
    mobile character varying(30),
    workphone character varying(30),
    address1 character varying(30),
    address2 character varying(30),
    zipcode character varying(30),
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    modified_on timestamp with time zone,
    photourl character varying(500),
    summary_bio character varying(1500),
    country uuid,
    created_by uuid,
    department uuid,
    modifeid_by uuid,
    org uuid,
    state uuid,
    supervisor uuid,
    enddate date,
    startdate date,
    school_name character varying(250),
    city character varying(30),
    personal_email character varying(50),
    is_superadmin boolean DEFAULT false,
    job_title character varying(150)
)
   